### ISSUE TITLE
[Bug] Cannot assign requested address while starting tubemq-master and webapi direct to localhost.

### ISSUE THREAD

**Issue by VWmin** [apache/incubator-inlong#1832] opened 2021-11-24 06:58 UTC
### What happened

I'm trying to deploy a tubemq master node on my ECS instance, but it failed and got logs below.

![image](https://user-images.githubusercontent.com/34272476/143187334-4d049bfa-2a24-48b4-838b-3de866b79c46.png)

I guess it is because the elastic network interface is not a real network interface in the instance, so it cannot be assigned.

Then, I replace the global IP address in conf/master.ini with 127.0.0.1. It works, the master node is deployed successfully. But the webapi got a problem, every webapi is going to 127.0.0.1:8080/webapi.htm?....

![dca64f3d55e6f893419cb8213bde6e8](https://user-images.githubusercontent.com/34272476/143188428-3afedb66-bd6c-4232-a5b3-9a1b183a6298.jpg)

### What you expected to happen

Cannot assign requested address maybe due to NAT, the ECS instance does not really have a global IP.

webapi may not be relative.

### How to reproduce

As described above.

### Environment

huaweicloud, Ubuntu 18.04 server 64bit.

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment] 2021-11-24 07:08
@VWmin, thanks, let me see.

By the way, can you find the cause of this?

**Comment by gosonzhang** [comment] 2021-11-25 02:22
@VWmin, this problem should be caused by the configuration file settings of master.ini, which lies in the default values of hostName and repHelperHost.

In order to make the compiled content run directly in containerization, which is convenient for the business to get started quickly, the server IP addresses of these two parameters are 127.0.0.1 (we don't know the business machine IP); but the business needs to be deployed on the machine, You must explicitly fill in the server IP to run normally.

I will modify the deployment document of TubeMQ to remind users of the handling of default values.

Thanks @VWmin

**Comment by VWmin** [comment] 2021-11-25 02:54
I used my real IP address in master.ini already, and the question has been verified caused by NAT. My ECS does not really have a physical network interface with global IP, it's a virtual network interface belonging to the cloud service. So, it can't be an effective address while deploying.

**Comment by gosonzhang** [comment] 2021-11-25 03:17
@VWmin, well, the problem is clear: the Console of TubeMQ Master does not support NAT penetration, when a user accesses it, it will construct some access links based on its own IP, so users outside the NAT must have access errors.

Users will not allow TubeMQ to operate outside the NAT when the system is actually online. I suggest you run it directly on your computer(PC or laptop),  whether it is Linux or Windows, it Can run.

**Comment by gosonzhang** [comment] 2021-11-25 07:23
@VWmin, whether there are other problems? If not, I'll close this issue.

thanks

**Comment by VWmin** [comment] 2021-11-25 09:12
> @VWmin, whether there are other problems? If not, I'll close this issue.
> 
> thanks

Yes, please close.

**Closed** 2021-11-25 09:17 UTC
Labels: bug
