### ISSUE TITLE
[Bug]the message of  inlong-agent sent is not filled with streamId

### ISSUE THREAD

**Issue by bruceneenhl** [apache/incubator-inlong#2024] opened 2021-12-17 10:00 UTC
### What happened

create a pulsar data access. the message of  inlong-agent sent is not filled with streamId

### What you expected to happen

format of message be right

### How to reproduce

create a pulsar data access. the message of  inlong-agent sent is not filled with streamId

### InLong version

master

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gosonzhang** [comment] 2021-12-17 12:06
@bruceneenhl, is the issue a duplicate of https://github.com/apache/incubator-inlong/issues/2023?

**Comment by gosonzhang** [comment] 2021-12-21 11:42
I'll close this issue

**Closed by gosonzhang** 2021-12-21 11:42 UTC
Labels: bug
